services:
  api:
    build: .
    ports:
      - "5000:5000"
      - "5678:5678"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - ./.env
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --no-debugger --host 0.0.0.0 --port 5000"]

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=myapp
    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data

volumes:
  postgres_data: 