"""empty message

Revision ID: 7fded81dff07
Revises: e8e305352f0e
Create Date: 2025-05-19 19:01:40.377076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fded81dff07'
down_revision = 'e8e305352f0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.create_unique_constraint('emailConstraint', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('emailConstraint', type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
